name: Generate Sitemap

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Sitemap
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml
          for file in $(find . -name "*.html"); do
            loc=$(echo $file | sed 's/^\.\///; s/\.html$//; s/index$//')
            echo "<url><loc>https://www.infusion.sk/${loc}</loc><changefreq>monthly</changefreq></url>" >> sitemap.xml
          done
          echo '</urlset>' >> sitemap.xml

      - name: Commit Sitemap
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add sitemap.xml
          git commit -m "Update sitemap" || echo "No changes to commit"
          git push
